# a github action on the dev branch that performs a build - test in a docker container
name: physionet-build-test

on:
  push:
    branches: 
      - dev
  pull_request:
    branches:
      - dev

jobs:
  container:
    runs-on: ubuntu-latest
    container: debian:10
    defaults:
      run:
        shell: bash

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_DB: physionet        
          POSTGRES_PASSWORD: password
          POSTGRES_USER: physionet
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: checkout physionet-build repo
        uses: actions/checkout@v2
      - name: update packages
        run: |
          apt-get update --yes
      - name: Install sudo package
        run: apt install sudo --yes
      - name: install and configure needed software
        run: |
          apt-get install python3-dev python3-pip build-essential zip wget python-virtualenv --yes
          virtualenv -p python3.7 env3
          source env3/bin/activate
          ln -sT .env.example .env
      - name: install repo dependencies
        run: |
          which pip3
          pip3 install -r requirements.txt
      - name: install libseccomp-dev for syscall filtering
        run: |
          apt-get install libseccomp-dev
      - name: install and setup wfdb
        run: |
          wget https://github.com/bemoody/wfdb/archive/10.6.2.tar.gz -O wfdb.tar.gz
          tar -xf wfdb.tar.gz
          (cd wfdb-* && ./configure --without-netfiles && make -C lib install && make -C data install)
      - name: run linker for newly installed software
        run: |
          ldconfig
      - name: install and setup lightwave
        run: |
          wget https://github.com/tompollard/lightwave/archive/dd9f2c5fb4a81012781b75b35d6f39714ddd1eec.tar.gz -O lightwave.tar.gz
          tar -xf lightwave.tar.gz
          (cd lightwave-* && make CGIDIR=/usr/local/bin sandboxed-server-ci)
          wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
      - name: install web driver - geckodriver 
        run: |
          mkdir geckodriver
          tar -xf geckodriver-v0.23.0-linux64.tar.gz -C geckodriver
          export PATH=$PATH:$PWD/geckodriver
      - name: setup and test physionet 
        run: |
          cd physionet-django
          python3 manage.py makemigrations --dry-run --no-input --check
          python3 manage.py resetdb
          python3 manage.py loaddemo
          python3 manage.py test --verbosity=3 --keepdb
      - name: check the amount of code being tested and print/report the result
        run: |
          coverage run --source='.' manage.py test --keepdb
          coverage report -m
